### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by casimir** [mawww/kak-ycmd#1]
Tried to use this with C++ and Go. For both I got the message "completed" but no matches proposed. Being my first contact with a kak file I can't figure if I did something wrong.

**Comment by mawww** [comment]
Hi, I do not use it anymore day to day, clang.kak is a little slower but more maintained. I tried and it does work here, you'll get ycmd output in the `*ycmd-output*` buffer, its likely that will give you an idea what is going on. In particular, YouCompleteMe wants a `.ycm_extra_confg.py` file.

**Comment by casimir** [comment]
Thanks for the buffer tip! After fixing some $PATH issues (gnu-coreutils need some setup to work seamlessly on OSX), I think all run correctly. I still have an error though, from `*ycmd-output*`: 

```
<some timestamp> - INFO - Dropping request with bad HMAC.
```

Any insight?

**Comment by mawww** [comment]
anything in the `*debug*` buffer ?

**Comment by casimir** [comment]
Nothing useful. Could it be the version of OpenSSL posing problem?

**Comment by casimir** [comment]
Looks like it really is a HMAC issue. It is empty for me. I don't find where the variable is supposed to be initialised, there is only one occurence of [${kak_opt_ycmd_hmac_key}](https://github.com/mawww/kak-ycmd/blob/master/ycmd.kak#L81).

edit: The variable is initialised this is the `base64` call that doesn't work.

```
## With some debug on line 81 I got the following log.

# echo "HMAC - ${kak_opt_ycmd_hmac_key}"
# key=$(echo -n "${kak_opt_ycmd_hmac_key}" | base64 -d -w0)
# echo "KEY - ${key}"

HMAC - Gb/54Rea9MqDp30ntqPDKQ==
base64: invalid input
KEY - 
base64: invalid input
```

Regarding version:

```
$ base64 --version
base64 (GNU coreutils) 8.24
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Simon Josefsson.
```

**Comment by mawww** [comment]
Hi, in %sh{ ... } blocks, $kak_opt_<option_name> is the syntax to access Kakoune option <option_name>, so here we access the ycmd_hmac_key option, which is declared line 5 and set line 47. You can display that option value with `:echo %opt{ycmd_hmac_key}`. the prompt wont provide option name completion for it because that is an hidden option, but the option should exist anyway.

**Comment by casimir** [comment]
I managed to get a key using `openssl base64` instead of `base64` but still ycmd considers it a bad HMAC, can't figure out why. Looks like this script isn't compatible with OSX 10.11. I will stop trying for now, thank you for your time.

**Comment by mawww** [comment]
Hi, Took a small look, I suspect for some reason base64 on your computer adds a final end of line in its output. Thats what the -w0 option is here to avoid, but I guess it just happened to work, I did not find a way to force openssl base64 not to do that, and tries with `tr -d '\n'` did not work well either.
